### PR TITLE
fix a typo in routes (case wrong)

### PR DESCRIPTION
**Pull request by derekja**
And I also updated webconfig files and package.json to use postcss-loader rather than the deprecated autoprefixer. (and fixed the production build issue I left last time.)

It was the capitalization change that prevented me from running on ubuntu 15.10, though, the other was just a warning.

Nice boilerplate, thanks!

### CODE REVIEW

**Comment by nicksp** [comment]
@derekja Thanks for providing your improvements Derek. Once i review them and align with the boilerplate's idea, will include your changes.

**Comment by nicksp** [comment]
Integrated just some bits of suggestions.
Don't see the point of integrating `subdivide` or `marktex`. I wanna keep my boilerplate lean and clean.

**Comment by derekja** [comment]
oh! oh no, I hope I haven't been pushing those bits towards you. Sorry, I'm
playing with some other new things in there. I though when I made a pull
request it made a snapshot at the time I requested. Sorry about that! I'll
pull request from a new branch in the future. Thanks,

Derek

On Tue, Mar 22, 2016 at 3:14 PM, Nick S. Plekhanov <notifications@github.com

**Comment by nicksp** [comment]
np Derek

**Pull request closed without merging**
